### ISSUE TITLE
Problem “Building an App with PHP 7” in Google Cloud

### ISSUE THREAD

**Issue by teresage** [GoogleCloudPlatform/php-docs-samples#1249]
I am following https://cloud.google.com/appengine/docs/standard/php7/building-app to build a PHP application in Google Cloud.

But after I deploy the application and go to the URL, I got following error message.

Slim Application Error
The application could not run because of the following error:
Details
Type: Error
Code: 0
Message: Using $this when not in object context
File: /workspace/src/controllers.php
Line: 36

The source code is here: https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/php72/getting-started/src/controllers.php

Do you know how to fix this? Thanks.

**Comment by ZaidBarghouthi** [comment]
The link provided is dead. Can you provide a working link?

**Comment by teresage** [comment]
> The link provided is dead. Can you provide a working link?

Hi, thanks for taking a look at this problem. I just tried the source code link, you are right, the code is not there any more! Maybe they found the code is out-dated, so they removed it. Never mind then. But I really appreciate your willingness to help. Have a great day!

**Comment by danmcdonald** [comment]
I am getting the same error mentioned above. I am following:
https://cloud.google.com/appengine/docs/standard/php7/building-app

Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Code: 0
Message: Using $this when not in object context
File: /workspace/src/controllers.php
Line: 36
Trace
 The source code is here:
https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/appengine/standard/getting-started/src/controllers.php

**Comment by bshaffer** [comment]
This has been fixed in #1296! Please update your `master` branch and you should be good to go.

 Some update to the slim framework broke these samples. Sorry for the inconvenience!
