### ISSUE TITLE
Not able to generate access_token

### ISSUE THREAD

**Issue by maxirodr** [GoogleCloudPlatform/php-docs-samples#1424]
Hello there. Command from PowerShell/cmd is working okay, and printing the access token that I copy/paste manually in cURL execution:

gcloud auth application-default print-access-token

The cURL is working okay when I manually use the result of the command, but from the example in this repo is not working at all:

https://github.com/GoogleCloudPlatform/php-docs-samples/blob/master/auth/index.php

(I'm using ProjectID and serviceAccountPath like the doc say)

There is a way to generate the access_token from this library so I can use it in the cURL executions?

**Comment by bshaffer** [comment]
@maxirodr Note that the file you're using, `index.php`, will only work when deployed to Google Cloud Platform infrastructure (GCE, GAE, GKE, Cloud Functions, etc). I imagine that's why you're not getting the behavior you expect.

As to your second question, you may want to look at the [`google/auth`](https://github.com/googleapis/google-auth-library-php) library for this. The way you could generate an access token there would be by doing something like this:

```php
$creds = Google\Auth\ApplicationDefaultCredentials::getCredentials();
echo $creds->fetchAuthToken();
```
