### ISSUE TITLE
message: "invalid value in the type field" error 

### ISSUE THREAD

**Issue by ma684351** [GoogleCloudPlatform/php-docs-samples#1778]
When using Workload Identity, field has an invalid value.  error 

## code
```php
$options = [
            'projectId' => 'test',
            'keyFilePath' => config('config.workload_identity_path'),
        ];
$pubSub = new PubSubClient($options);

// Get an instance of a previously created topic.
$topic = $pubSub->topic('test-topic');

// Publish a message to the topic.
$topic->publish((new MessageBuilder)->setData('test publish')->build());ï
```

## output

```
/vendor/google/cloud-core/src/RequestWrapper.php(207): Google\Cloud\Core\RequestWrapper->convertToGoogleException(Object(InvalidArgumentException)) #1
/vendor/google/cloud-core/src/RestTrait.php(99): Google\Cloud\Core\RequestWrapper->send(Object(GuzzleHttp\Psr7\Request), Array) #2
/vendor/google/cloud-pubsub/src/Connection/Rest.php(113): Google\Cloud\PubSub\Connection\Rest->send('topics', 'publish', Array) #3 
/vendor/google/cloud-pubsub/src/Topic.php(495): Google\Cloud\PubSub\Connection\Rest->publishMessage(Array) #4 
/vendor/google/cloud-pubsub/src/Topic.php(448): Google\Cloud\PubSub\Topic->publishBatch(Array, Array) #5 
/app/Http/Controllers/Admin/AnalyticsReportsController.php(211): Google\Cloud\PubSub\Topic->publish(Object(Google\Cloud\PubSub\Message)) #6 [internal function]:
```

**Comment by vishwarajanand** [comment]
@ma684351 from the provided info, the exact issue isn't very clear. 

From what I can tell, `RequestWrapper->send` gives Google Exception if either the auth params were incorrect (which could be due to `config('config.workload_identity_path')` not returning a valid path) OR the request was actually rejected by the server. Hope it helps in your debugging.

**Comment by ma684351** [comment]
@vishwarajanand 
I think not considered  `type: external_account` this code
https://github.com/googleapis/google-auth-library-php/blob/main/src/CredentialsLoader.php#L126-L150

**Comment by vishwarajanand** [comment]
@ma684351 If you are using workflow identity federation, then rather than `external_account` I think it should go under `impersonated_service_account`, read more about it [here](https://cloud.google.com/iam/docs/workload-identity-federation#:~:text=The%20token%20exchange%20flow%20returns%20a%20federated%20access%20token.%20You%20can%20use%20this%20token%20to%20impersonate%20a%20service%20account%20and%20obtain%20a%20short%2Dlived%20OAuth%202.0%20access%20token.).

Is there a reason you are piching for `external_account` ?

**Comment by ma684351** [comment]
@vishwarajanand 
I'm looking to call pub/sub on EC2 without using service_account.
more secure method than keeping credentials on a EC2 and I'd love to use it for my PHP projects.

**Comment by vishwarajanand** [comment]
This would need some changes in our upstream libraries to support.
I would open an issue and close this.
