### ISSUE TITLE
WP Personal data export fails as it tries to write to the instance fs instead of storage bucket

### ISSUE THREAD

**Issue by jdbrew** [GoogleCloudPlatform/php-docs-samples#617]
Using php-docs-samples/appengine/wordpress/
Wordpress’ Personal data export fails as it tries to write to the instance fs instead of storage bucket.

WP 4.9.6
php-docs-samples - latest master

```PHP Warning:  fopen(gs:/[PROJECTNAME].appspot.com/wp-personal-data-exports/wp-personal-data-file-[EMAIL]-[HASH].html): failed to open stream: Read-only file system in /base/data/home/apps/g~[PROJECTNAME]/[DATESTRING.HASH]/wordpress/wp-admin/includes/file.php on line 1914```

**Comment by bshaffer** [comment]
This is most likely because the stream wrapper for GCS hasn't been enabled. This can be done using the [StreamWrapper class](https://github.com/googleapis/google-cloud-php-storage/blob/master/src/StreamWrapper.php):

```php
use Google\Cloud\Storage\StorageClient;
use Google\Cloud\Storage\StreamWrapper;

$storage = new StorageClient(['projectId' => 'YOUR_PROJECT_ID']);
StreamWrapper::register($storage);
```

See the [StorageClient](https://github.com/googleapis/google-cloud-php-storage/blob/master/src/StorageClient.php#L91) for more information about initializing the `StorageClient`
